[phases.setup]
nixPkgs = ['maven', 'jdk21']

[phases.build]
cmds = ['mvn clean package -DskipTests']

[phases.start]
cmd = 'java -Dserver.port=$PORT -jar target/banking-management-system-0.0.1-SNAPSHOT.jar'
